### ISSUE TITLE
a few kicad files crash instantly when opeing

### ISSUE THREAD

**Issue by NataniSi** [bismarx-v1/Sumec-MiniSumo#27]
A few kicad files crash instantly when opeing

Occurs when opening through the ".kicad_pro" file or when opening files individually.
Affected files:

[-PCB-/_archive_old/SUMEC_SMD-V2/MECHANICS.kicad_sch](https://github.com/bismarx-v1/Sumec-MiniSumo/blob/a65e63b65f2ede6e8036a4a3e1dbe55981a46eda/-PCB-/_archive_old/SUMEC_SMD-V2/MECHANICS.kicad_sch)
[-PCB-/_archive_old/SUMEC_SMD-V2/POWER SUPPLY.kicad_sch](https://github.com/bismarx-v1/Sumec-MiniSumo/blob/a65e63b65f2ede6e8036a4a3e1dbe55981a46eda/-PCB-/_archive_old/SUMEC_SMD-V2/POWER%20SUPPLY.kicad_sch)
[-PCB-/_archive_old/SUMEC_SMD-V2/SENSORS.kicad_sch](https://github.com/bismarx-v1/Sumec-MiniSumo/blob/a65e63b65f2ede6e8036a4a3e1dbe55981a46eda/-PCB-/_archive_old/SUMEC_SMD-V2/SENSORS.kicad_sch)
[-PCB-/SUMEC_MK_IV/MECHANICS.kicad_sch](https://github.com/bismarx-v1/Sumec-MiniSumo/blob/a65e63b65f2ede6e8036a4a3e1dbe55981a46eda/-PCB-/SUMEC_MK_IV/MECHANICS.kicad_sch)
[-PCB-/SUMEC_MK_IV/POWER_SUPPLY.kicad_sch](https://github.com/bismarx-v1/Sumec-MiniSumo/blob/a65e63b65f2ede6e8036a4a3e1dbe55981a46eda/-PCB-/SUMEC_MK_IV/POWER_SUPPLY.kicad_sch)
[-PCB-/SUMEC_MK_IV/SENSORS.kicad_sch](https://github.com/bismarx-v1/Sumec-MiniSumo/blob/a65e63b65f2ede6e8036a4a3e1dbe55981a46eda/-PCB-/SUMEC_MK_IV/SENSORS.kicad_sch)

**Comment by bismarx-v1** [comment]
Maybe gitignore affects this? Ill change gitignore let me know if its going to fix it.

**Comment by bismarx-v1** [comment]
I think this one is fixed
