### ISSUE TITLE
useless suff in docs, missing needed stuff

### ISSUE THREAD

**Issue by ghost** [bismarx-v1/Sumec-MiniSumo#35]
no main in the code folder is a docs file called "FULL SCHEMATIC PDF.pdf". my issues are that it ahs spaces in the name, and that's wrong. a bigger issue i have is that there is no pcb version number. glad there is the big logo though. we figured out it's probably the mk3 pcb, but each page has a table in the bottom right corner and the file has a name, yet no version number to be found. :3

**Comment by bismarx-v1** [comment]
fixed
